replicaCount: 1

podLabels:
  environment: dev

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi
