replicaCount: 3

podLabels:
  environment: prod

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
