replicaCount: 2

nameOverride: ""
fullnameOverride: ""

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

podLabels: {}

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

service:
  portName: http
  port: 80
  protocol: TCP

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

terminationGracePeriodSeconds: 30
