replicaCount: 2

podLabels:
  environment: stg

image:
  repository: nginx
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
